[tool.poetry]
package-mode = false
name = "test-text-to-sql"
version = "0.1.0"
description = ""
authors = ["Nicolas De Horta <ext-n.dehorta@rappi.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.12,<4.0"
langchain = ">=0.3.23,<0.4.0"
langgraph = ">=0.3.27,<0.4.0"
sqlalchemy = ">=2.0.40,<3.0.0"
python-dotenv = "^1.1.0"
psycopg2 = "^2.9.10"
langchain-openai = "^0.3.12"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.flake8]
max-line-length = 190
