from langgraph.graph import StateGraph, START, END
from langgraph.graph.message import add_messages
from typing import TypedDict, Annotated
from db_manager import DatabaseManager
from langchain_openai import ChatOpenAI
from prompt import prompt, prompt_json
import os
from langchain_core.messages import AIMessage
import json
import requests

class GraphState(TypedDict):
    messages: Annotated[list, add_messages]


llm = ChatOpenAI(
    model="llama3-70b-8192",
    base_url="https://api.groq.com/openai/v1",
    api_key=os.getenv("GROQ_API_KEY")
)

db = DatabaseManager()


def generate_sql_query(state: GraphState):
    """
    Takes a GraphState, generates a SQL query based on the last message in the
    state, and returns a new GraphState with the SQL query as a message.

    The SQL query is generated by passing the last message in the state to the
    prompt | llm chain. The prompt is a ChatPromptTemplate that uses the
    question from the state and the schema of the database to generate a prompt.
    The llm is a ChatOpenAI model that takes the prompt and returns a message
    with the generated SQL query.

    The function prints the question and the generated SQL query, and returns a
    new GraphState with the SQL query as an additional message.
    """
    chain = prompt | llm
    question = state["messages"][-1].content
    sql = chain.invoke({"question": question, "schema": db.get_schema()})
    content = sql.content
    print("====== \n" + "QUESTION: " + question)
    print("====== \n" + "SQL: " + content)
    print("======+++++++++++++++++++++ \n")
    
    return {"messages":
            state["messages"] + [{"role": "assistant", "content": content}]}


def run_query(state: GraphState):
    
    """
    Executes a SQL query derived from the last message in the provided state
    and returns the result as a JSON-formatted string.

    Args:
        state (GraphState): The current state containing a list of messages,
                            where the last message holds the SQL query to execute.

    Returns:
        dict: A dictionary containing the updated messages list, with the query
              result appended as an AIMessage in JSON format.
    """

    query = state["messages"][-1].content
    # print(f"esta es la query que se hace: {query} \n")
    df = db.raw_query_invoke(query)
    json_data = df.to_json(orient="records")

    print("====== \n" + "RESULT: " + json_data)

    return {"messages": state["messages"] + [AIMessage(content=json_data)]}


def generate_sql_query_json(state: GraphState):
    chain = prompt_json | llm
    question = state["messages"][-1].content

    response = chain.invoke({"question": question, "schema": db.get_schema()})
    content = response.content

    # Parse the JSON output
    parsed = json.loads(content)
    thoughts = parsed.get("thoughts", "")
    sql = parsed.get("sql", "")

    print("====== \n" + "QUESTION: " + question)
    print("======+++++++++++++++++++++ \n")
    print("====== \n" + "THOUGHTS: " + thoughts)
    print("======+++++++++++++++++++++ \n")
    print("====== \n" + "SQL: " + sql)

    return {
        "messages": state["messages"] + [
            {"role": "assistant", "content": sql, "thoughts": thoughts}
        ]
    }
    
def call_api_node(state: GraphState):
    """
    Calls an external API with the SQL generated and returns the API's response.
    """

    # La SQL generada es el penúltimo mensaje (último es el resultado de la query)
    question = state["messages"][0].content
    thoughts = state["messages"][-3].content
    sql = state["messages"][-2].content
    result = state["messages"][-1].content

    payload = {
        "Question": f"La pregunta fue {question}",
        "query": sql,
        "thoughts": thoughts,
        "result": result,
        "metadata": "some example metadata"
    }

    # Simulamos una llamada a un API dummy
    response = requests.post("http://localhost:8000/nodum_test", json=payload)
    if response.status_code == 200:
        api_response = response.json()
        message = f"API call successful. Response data: {api_response.get('json', {})}"
    else:
        message = f"API call failed with status code {response.status_code}"

    print("====== \n" + "API CALL RESULT: " + message)

    return 


builder = StateGraph(GraphState)

# builder.add_node("generate_sql_query", generate_sql_query)
# builder.add_node("run_query", run_query)

# builder.add_edge(START, "generate_sql_query")
# builder.add_edge("generate_sql_query", "run_query")
# builder.add_edge("run_query", END)

builder.add_node("generate_sql_query_json", generate_sql_query_json)
builder.add_node("run_query", run_query)
builder.add_node("call_api_node", call_api_node)

builder.add_edge(START, "generate_sql_query_json")
builder.add_edge("generate_sql_query_json", "run_query")
builder.add_edge("run_query", "call_api_node")
builder.add_edge("call_api_node", END)

graph = builder.compile()
